Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

Outputs:
  GitHubOIDCProviderARN:
    Value: !Ref GitHubOIDCProvider
    Export:
      Name: GitHubOIDCProviderARN
