Parameters:
  WebSiteS3BucketName:
    Type: String
  GitHubOrg:
    Type: String
  RepositoryName:
    Type: String

Resources:
  WebSiteS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebSiteS3BucketName

  GitHubActionsIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Federated: !ImportValue GitHubOIDCProviderArn
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*
      Policies:
        - PolicyName: AllowPutObjectToBucket
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub ${WebSiteS3Bucket.Arn}/*
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Ref WebSiteS3Bucket.Arn

